name: khono
description: A social learning platform built with Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # UI and Navigation
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  flutter_animate: ^4.5.0
  page_transition: ^2.1.0

  # State Management
  provider: ^6.1.5
  flutter_riverpod: ^2.6.1

  # Charts and Data Visualization
  fl_chart: ^0.68.0

  # Utilities
  shared_preferences: ^2.5.3
  path_provider: ^2.1.4
  url_launcher: ^6.3.1
  intl: ^0.20.2
  go_router: ^12.1.3
  flutter_local_notifications: ^18.0.0
  timezone: ^0.9.1
  
  # Image Picker
  image_picker: ^1.0.4
  
  # SVG Support
  flutter_svg: ^2.0.10+1
  
  # Database
  http: ^1.4.0
  crypto: ^3.0.6
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/videos/
    - assets/audios/
    - assets/rive_animations/
    - assets/pdfs/
    - assets/jsons/
