include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - frontend/**
    - Flow-Space/**
    - build/**
    - .dart_tool/**
  errors:
    require_trailing_commas: ignore

linter:
  rules:
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    unnecessary_string_escapes: false
    prefer_const_constructors_in_immutables: true
    public_member_api_docs: false
    require_trailing_commas: true
